- name: == Xen == Destroying Virtual Guest 
  shell: /usr/local/bin/destroyvm {{ inventory_hostname }}
  ignore_errors: yes
  delegate_to: "{{ xen_host }}"


- name: == Xen == Creating kickstart to provision VM[s]
  template: src=../templates/kickstarts/c{{ centos_dist }}-xen-guest.cfg.j2 dest=/var/lib/libvirt/local-kickstarts/{{ inventory_hostname }}.cfg
  delegate_to: "{{ xen_host }}"

- name: == Xen == Creating temporary virt-install command
  template: src=../templates/ansible-virt-install-xen.j2 dest=/var/lib/libvirt/virt-install-{{ inventory_hostname }} mode=0750 owner=root group=root
  delegate_to: "{{ xen_host }}"

- name: == Xen == Provisining the Virtual Guest[s]
  command: /var/lib/libvirt/virt-install-{{ inventory_hostname }}
  delegate_to: "{{ xen_host }}"

- name: == Xen == Waiting for sshd to be available on the deployed node
  wait_for: port=22 host={{ ip }} timeout=1200 
  delegate_to: "{{ xen_host }}"

   
    
