- name: == Blade == Generate kickstart file[s] for QA node[s]  
  template: 
    src: ../templates/kickstarts/c{{ centos_dist }}-blade.cfg.j2
    dest: /var/www/qa/ks/{{ inventory_hostname }}-ks.cfg 
    mode: 0755
  delegate_to: "{{ ks_node }}" 
  
- name: == Blade == Generating the tftp configuration boot file
  template: 
    src: ../templates/pxeboot.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/01-{{ mac_address | lower | replace(":","-") }} 
    mode: 0755
  delegate_to: "{{ tftpd_node }}"

- name: == Blade == Ensuring blade is powered off
  command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis power off
  delegate_to: "{{ deploy_node }}"

- name: == Blade == Pausing ...
  pause:
    seconds: 8

- name: == Blade == configuring pxe boot
  command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis bootdev pxe
  delegate_to: "{{ deploy_node }}"

- name: == Blade == Pausing ...
  pause:
    seconds: 2

- name: == Blade == Ensuring blade is powered on
  command: ipmitool -I lanplus -U {{ ipmi_user }} -P {{ ipmi_pass }} -H {{ ipmi_ip }} chassis power on
  delegate_to: "{{ deploy_node }}"

- name: == Blade == Waiting for host to be reachable
  wait_for: host={{ ip }} port=22 timeout=1200 
  delegate_to: "{{ tftpd_node }}"
